### ISSUE TITLE
Cant run setup.exe

### ISSUE THREAD

**Issue by L3ungj** [someone-s/Christmas-Bot#22]
Version:  r1-5-2-0
When I run setup.exe, this error happens:
`Unhandled exception. System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.                      at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)                                                                                                 at System.Text.Json.Utf8JsonReader.Read()                                                                               at System.Text.Json.JsonDocument.TryParseValue(Utf8JsonReader& reader, JsonDocument& document, Boolean shouldThrow)     at System.Text.Json.JsonDocument.TryParseValue(Utf8JsonReader& reader, JsonDocument& document)                          at Christmas_bot.AuthHandle.TryGetToken(String& token)                                                                  at Christmas_bot.Bot.RunAsync()                                                                                         at Christmas_bot.Program.Main(String[] args)   `

My config.json:
{
	"token": "my_token"
}

**Comment by L3ungj** [comment]
put config.json to documents/christmas-bot, solved

**Comment by someone-s** [comment]
bruh
